sudo: required
services:
  - docker

before_install:
  - docker build -t aslau4/docker-react -f Dockerfile.dev .

#https://stackoverflow.com/questions/55991641/npm-test-coverage-never-exits
script:
  - docker run -e CI=true aslau4/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-2-202868600584"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"